# ---------------------------------------------------------------------------------------- #
# Makefile
# ---------------------------------------------------------------------------------------- #


.PHONY: all clean


all:
	@echo "Makefile lanched for $(shell basename ${PWD})"


clean:
	@echo "cleaning the module"
