# ---------------------------------------------------------------------------------------- #
# Makefile
# ---------------------------------------------------------------------------------------- #


.PHONY: all clean


all:
	@echo "Makefile lanched in $(shell basename ${PWD}) for 01"


test:
	@echo "Testing module 03"


clean:
	@echo "cleaning the module 01"
