# ---------------------------------------------------------------------------------------- #
# Makefile
# ---------------------------------------------------------------------------------------- #


.PHONY: all clean


all:
	@echo "Makefile lanched in $(shell basename ${PWD}) for 03"


test:
	@echo "Testing module 03"


clean:
	@echo "cleaning the module 03"
